# Generated by Django 4.2.7 on 2025-10-08 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('forecast_date', models.DateField(help_text='Date of the forecast')),
                ('forecast_time', models.TimeField(help_text='Time of the forecast')),
                ('temperature_min', models.DecimalField(decimal_places=2, help_text='Minimum temperature in Celsius', max_digits=5)),
                ('temperature_max', models.DecimalField(decimal_places=2, help_text='Maximum temperature in Celsius', max_digits=5)),
                ('humidity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pressure', models.PositiveIntegerField()),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_direction', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('weather_condition', models.CharField(max_length=100)),
                ('weather_description', models.CharField(max_length=255)),
                ('weather_icon', models.CharField(max_length=10)),
                ('precipitation_probability', models.DecimalField(decimal_places=2, help_text='Probability of precipitation (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('rainfall_amount', models.DecimalField(decimal_places=2, default=0, help_text='Expected rainfall amount (mm)', max_digits=5)),
                ('data_source', models.CharField(default='openweathermap', max_length=50)),
                ('api_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather Forecast',
                'verbose_name_plural': 'Weather Forecasts',
                'ordering': ['forecast_date', 'forecast_time'],
                'indexes': [models.Index(fields=['latitude', 'longitude', 'forecast_date'], name='weather_int_latitud_3842e5_idx'), models.Index(fields=['forecast_date'], name='weather_int_forecas_739635_idx'), models.Index(fields=['location_name'], name='weather_int_locatio_df9266_idx')],
                'unique_together': {('latitude', 'longitude', 'forecast_date', 'forecast_time')},
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate', max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate', max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location_name', models.CharField(blank=True, help_text="Human-readable location name (e.g., 'Lusaka, Zambia')", max_length=255, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, help_text='Temperature in Celsius', max_digits=5)),
                ('feels_like', models.DecimalField(decimal_places=2, help_text='Feels like temperature in Celsius', max_digits=5)),
                ('humidity', models.PositiveIntegerField(help_text='Humidity percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('pressure', models.PositiveIntegerField(help_text='Atmospheric pressure in hPa')),
                ('wind_speed', models.DecimalField(decimal_places=2, help_text='Wind speed in m/s', max_digits=5)),
                ('wind_direction', models.PositiveIntegerField(help_text='Wind direction in degrees (0-360)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('weather_condition', models.CharField(help_text="Weather condition (e.g., 'Clear', 'Rain', 'Clouds')", max_length=100)),
                ('weather_description', models.CharField(help_text='Detailed weather description', max_length=255)),
                ('weather_icon', models.CharField(help_text='Weather icon code from API', max_length=10)),
                ('rainfall_1h', models.DecimalField(decimal_places=2, default=0, help_text='Rainfall in last 1 hour (mm)', max_digits=5)),
                ('rainfall_3h', models.DecimalField(decimal_places=2, default=0, help_text='Rainfall in last 3 hours (mm)', max_digits=5)),
                ('data_source', models.CharField(default='openweathermap', help_text="Source of weather data (e.g., 'openweathermap')", max_length=50)),
                ('api_response', models.JSONField(help_text='Raw API response for debugging')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather Data',
                'verbose_name_plural': 'Weather Data',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='weather_int_latitud_15281d_idx'), models.Index(fields=['updated_at'], name='weather_int_updated_9a85f3_idx'), models.Index(fields=['location_name'], name='weather_int_locatio_44d32f_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('alert_type', models.CharField(help_text="Type of alert (e.g., 'Heavy Rain', 'Heat Wave', 'Storm')", max_length=100)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('extreme', 'Extreme')], default='moderate', max_length=50)),
                ('title', models.CharField(help_text='Alert title/headline', max_length=255)),
                ('description', models.TextField(help_text='Detailed alert description')),
                ('start_time', models.DateTimeField(help_text='When the alert starts')),
                ('end_time', models.DateTimeField(help_text='When the alert ends')),
                ('data_source', models.CharField(default='openweathermap', max_length=50)),
                ('api_response', models.JSONField()),
                ('is_active', models.BooleanField(default=True, help_text='Whether alert is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather Alert',
                'verbose_name_plural': 'Weather Alerts',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='weather_int_latitud_85be1b_idx'), models.Index(fields=['is_active', 'end_time'], name='weather_int_is_acti_ce8eb3_idx'), models.Index(fields=['severity'], name='weather_int_severit_782ce7_idx')],
            },
        ),
    ]
