# Generated by Django 4.2.7 on 2025-10-07 13:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Field name or identifier (e.g., "North Field", "Plot 1")', max_length=100)),
                ('location', models.CharField(blank=True, help_text='Detailed field location (e.g., "Chilanga District, Lusaka")', max_length=200)),
                ('region', models.CharField(choices=[('lusaka', 'Lusaka'), ('central', 'Central Province'), ('southern', 'Southern Province'), ('eastern', 'Eastern Province'), ('copperbelt', 'Copperbelt'), ('northern', 'Northern Province'), ('western', 'Western Province'), ('luapula', 'Luapula'), ('muchinga', 'Muchinga'), ('northwestern', 'North-Western')], default='lusaka', help_text='Zambian province where the field is located', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for precise weather data', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for precise weather data', max_digits=9, null=True)),
                ('area', models.DecimalField(decimal_places=2, help_text='Field area in hectares', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('crop_type', models.CharField(choices=[('Maize', 'Maize'), ('Wheat', 'Wheat'), ('Rice', 'Rice'), ('Tomatoes', 'Tomatoes'), ('Potatoes', 'Potatoes'), ('Cotton', 'Cotton')], help_text='Type of crop planted in this field', max_length=50)),
                ('planting_date', models.DateField(help_text='Date when the crop was planted')),
                ('soil_type', models.CharField(choices=[('Clay', 'Clay'), ('Loam', 'Loam'), ('Sandy', 'Sandy'), ('Silty', 'Silty')], help_text='Primary soil type in this field', max_length=50)),
                ('current_soil_moisture', models.IntegerField(default=50, help_text='Current soil moisture percentage (0-100%)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('irrigation_method', models.CharField(choices=[('drip', 'Drip Irrigation'), ('sprinkler', 'Sprinkler Irrigation'), ('flood', 'Flood/Furrow Irrigation'), ('rainfed', 'Rain-fed (No Irrigation)')], default='rainfed', help_text='Primary irrigation method used', max_length=50)),
                ('current_season', models.CharField(choices=[('Dry', 'Dry Season (May-October)'), ('Wet', 'Wet Season (November-April)')], default='Dry', help_text='Current growing season', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this field')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this field is currently in use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='Owner of this field', on_delete=django.db.models.deletion.CASCADE, related_name='fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='fields_fiel_user_id_642798_idx'), models.Index(fields=['is_active'], name='fields_fiel_is_acti_ed6a6b_idx')],
            },
        ),
    ]
