# Generated by Django 4.2.7 on 2025-10-09 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive email notifications for irrigation schedules')),
                ('push_notifications', models.BooleanField(default=True, help_text='Receive push notifications in the browser')),
                ('irrigation_reminders', models.BooleanField(default=True, help_text='Receive reminders for scheduled irrigation')),
                ('weather_alerts', models.BooleanField(default=True, help_text='Receive weather-related alerts')),
                ('temperature_unit', models.CharField(choices=[('celsius', 'Celsius (°C)'), ('fahrenheit', 'Fahrenheit (°F)')], default='celsius', help_text='Preferred temperature unit', max_length=20)),
                ('volume_unit', models.CharField(choices=[('liters', 'Liters (L)'), ('gallons', 'Gallons (gal)')], default='liters', help_text='Preferred volume unit', max_length=20)),
                ('time_format', models.CharField(choices=[('12h', '12-hour (AM/PM)'), ('24h', '24-hour')], default='24h', help_text='Preferred time format', max_length=10)),
                ('default_irrigation_duration', models.PositiveIntegerField(default=30, help_text='Default irrigation duration in minutes')),
                ('default_irrigation_method', models.CharField(choices=[('drip', 'Drip Irrigation'), ('sprinkler', 'Sprinkler System'), ('flood', 'Flood Irrigation'), ('manual', 'Manual Watering')], default='drip', help_text='Default irrigation method', max_length=50)),
                ('dashboard_refresh_interval', models.PositiveIntegerField(default=300, help_text='Dashboard auto-refresh interval in seconds (0 = disabled)')),
                ('items_per_page', models.PositiveIntegerField(default=10, help_text='Number of items to display per page in lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
    ]
